// Generated by gencpp from file ardupilot_sitl_gazebo_plugin/ReleaseApmLapseLockRequest.msg
// DO NOT EDIT!


#ifndef ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_RELEASEAPMLAPSELOCKREQUEST_H
#define ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_RELEASEAPMLAPSELOCKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardupilot_sitl_gazebo_plugin
{
template <class ContainerAllocator>
struct ReleaseApmLapseLockRequest_
{
  typedef ReleaseApmLapseLockRequest_<ContainerAllocator> Type;

  ReleaseApmLapseLockRequest_()
    : process_id()  {
    }
  ReleaseApmLapseLockRequest_(const ContainerAllocator& _alloc)
    : process_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _process_id_type;
  _process_id_type process_id;




  typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReleaseApmLapseLockRequest_

typedef ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<std::allocator<void> > ReleaseApmLapseLockRequest;

typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest > ReleaseApmLapseLockRequestPtr;
typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest const> ReleaseApmLapseLockRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardupilot_sitl_gazebo_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a19d2ed2d6b55934bac7cd67cfed8983";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa19d2ed2d6b55934ULL;
  static const uint64_t static_value2 = 0xbac7cd67cfed8983ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardupilot_sitl_gazebo_plugin/ReleaseApmLapseLockRequest";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string process_id\n\
";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.process_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReleaseApmLapseLockRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest_<ContainerAllocator>& v)
  {
    s << indent << "process_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.process_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_RELEASEAPMLAPSELOCKREQUEST_H
