// Generated by gencpp from file ardupilot_sitl_gazebo_plugin/ReleaseApmLapseLock.msg
// DO NOT EDIT!


#ifndef ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_RELEASEAPMLAPSELOCK_H
#define ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_RELEASEAPMLAPSELOCK_H

#include <ros/service_traits.h>


#include <ardupilot_sitl_gazebo_plugin/ReleaseApmLapseLockRequest.h>
#include <ardupilot_sitl_gazebo_plugin/ReleaseApmLapseLockResponse.h>


namespace ardupilot_sitl_gazebo_plugin
{

struct ReleaseApmLapseLock
{

typedef ReleaseApmLapseLockRequest Request;
typedef ReleaseApmLapseLockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReleaseApmLapseLock
} // namespace ardupilot_sitl_gazebo_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock > {
  static const char* value()
  {
    return "c05d882edd165bc15552be77c9967c82";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock&) { return value(); }
};

template<>
struct DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock > {
  static const char* value()
  {
    return "ardupilot_sitl_gazebo_plugin/ReleaseApmLapseLock";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock&) { return value(); }
};


// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest> should match 
// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock > 
template<>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest> should match 
// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock > 
template<>
struct DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest>
{
  static const char* value()
  {
    return DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockResponse> should match 
// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock > 
template<>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockResponse> should match 
// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock > 
template<>
struct DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockResponse>
{
  static const char* value()
  {
    return DataType< ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::ReleaseApmLapseLockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_RELEASEAPMLAPSELOCK_H
