// Generated by gencpp from file ardupilot_sitl_gazebo_plugin/TakeApmLapseLockResponse.msg
// DO NOT EDIT!


#ifndef ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCKRESPONSE_H
#define ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardupilot_sitl_gazebo_plugin
{
template <class ContainerAllocator>
struct TakeApmLapseLockResponse_
{
  typedef TakeApmLapseLockResponse_<ContainerAllocator> Type;

  TakeApmLapseLockResponse_()
    : nb_holders(0)  {
    }
  TakeApmLapseLockResponse_(const ContainerAllocator& _alloc)
    : nb_holders(0)  {
  (void)_alloc;
    }



   typedef int32_t _nb_holders_type;
  _nb_holders_type nb_holders;




  typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TakeApmLapseLockResponse_

typedef ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<std::allocator<void> > TakeApmLapseLockResponse;

typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse > TakeApmLapseLockResponsePtr;
typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse const> TakeApmLapseLockResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardupilot_sitl_gazebo_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "253e7166b1565daeac58fa52440f47e2";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x253e7166b1565daeULL;
  static const uint64_t static_value2 = 0xac58fa52440f47e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardupilot_sitl_gazebo_plugin/TakeApmLapseLockResponse";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nb_holders\n\
\n\
";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nb_holders);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeApmLapseLockResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse_<ContainerAllocator>& v)
  {
    s << indent << "nb_holders: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nb_holders);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCKRESPONSE_H
