// Generated by gencpp from file ardupilot_sitl_gazebo_plugin/TakeApmLapseLock.msg
// DO NOT EDIT!


#ifndef ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCK_H
#define ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCK_H

#include <ros/service_traits.h>


#include <ardupilot_sitl_gazebo_plugin/TakeApmLapseLockRequest.h>
#include <ardupilot_sitl_gazebo_plugin/TakeApmLapseLockResponse.h>


namespace ardupilot_sitl_gazebo_plugin
{

struct TakeApmLapseLock
{

typedef TakeApmLapseLockRequest Request;
typedef TakeApmLapseLockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeApmLapseLock
} // namespace ardupilot_sitl_gazebo_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock > {
  static const char* value()
  {
    return "88fb6d40bf2b0fa731238774f37356ca";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock&) { return value(); }
};

template<>
struct DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock > {
  static const char* value()
  {
    return "ardupilot_sitl_gazebo_plugin/TakeApmLapseLock";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock&) { return value(); }
};


// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest> should match 
// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock > 
template<>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest> should match 
// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock > 
template<>
struct DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest>
{
  static const char* value()
  {
    return DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse> should match 
// service_traits::MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock > 
template<>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse> should match 
// service_traits::DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock > 
template<>
struct DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse>
{
  static const char* value()
  {
    return DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLock >::value();
  }
  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCK_H
