// Generated by gencpp from file ardupilot_sitl_gazebo_plugin/TakeApmLapseLockRequest.msg
// DO NOT EDIT!


#ifndef ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCKREQUEST_H
#define ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardupilot_sitl_gazebo_plugin
{
template <class ContainerAllocator>
struct TakeApmLapseLockRequest_
{
  typedef TakeApmLapseLockRequest_<ContainerAllocator> Type;

  TakeApmLapseLockRequest_()
    : process_id()
    , max_duration(0.0)  {
    }
  TakeApmLapseLockRequest_(const ContainerAllocator& _alloc)
    : process_id(_alloc)
    , max_duration(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _process_id_type;
  _process_id_type process_id;

   typedef float _max_duration_type;
  _max_duration_type max_duration;




  typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TakeApmLapseLockRequest_

typedef ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<std::allocator<void> > TakeApmLapseLockRequest;

typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest > TakeApmLapseLockRequestPtr;
typedef boost::shared_ptr< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest const> TakeApmLapseLockRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardupilot_sitl_gazebo_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80b65c80b1a961c9c83f328f9dcdec20";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80b65c80b1a961c9ULL;
  static const uint64_t static_value2 = 0xc83f328f9dcdec20ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardupilot_sitl_gazebo_plugin/TakeApmLapseLockRequest";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string process_id\n\
float32 max_duration\n\
";
  }

  static const char* value(const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.process_id);
      stream.next(m.max_duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeApmLapseLockRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardupilot_sitl_gazebo_plugin::TakeApmLapseLockRequest_<ContainerAllocator>& v)
  {
    s << indent << "process_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.process_id);
    s << indent << "max_duration: ";
    Printer<float>::stream(s, indent + "  ", v.max_duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUPILOT_SITL_GAZEBO_PLUGIN_MESSAGE_TAKEAPMLAPSELOCKREQUEST_H
