// Generated by gencpp from file region_events/region_eventsResponse.msg
// DO NOT EDIT!


#ifndef REGION_EVENTS_MESSAGE_REGION_EVENTSRESPONSE_H
#define REGION_EVENTS_MESSAGE_REGION_EVENTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace region_events
{
template <class ContainerAllocator>
struct region_eventsResponse_
{
  typedef region_eventsResponse_<ContainerAllocator> Type;

  region_eventsResponse_()
    : stepped(false)  {
    }
  region_eventsResponse_(const ContainerAllocator& _alloc)
    : stepped(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stepped_type;
  _stepped_type stepped;




  typedef boost::shared_ptr< ::region_events::region_eventsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::region_events::region_eventsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct region_eventsResponse_

typedef ::region_events::region_eventsResponse_<std::allocator<void> > region_eventsResponse;

typedef boost::shared_ptr< ::region_events::region_eventsResponse > region_eventsResponsePtr;
typedef boost::shared_ptr< ::region_events::region_eventsResponse const> region_eventsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::region_events::region_eventsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::region_events::region_eventsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace region_events

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::region_events::region_eventsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::region_events::region_eventsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::region_events::region_eventsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::region_events::region_eventsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::region_events::region_eventsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::region_events::region_eventsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::region_events::region_eventsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9df8f2f743a5e6ba6981f0ecdb4d3549";
  }

  static const char* value(const ::region_events::region_eventsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9df8f2f743a5e6baULL;
  static const uint64_t static_value2 = 0x6981f0ecdb4d3549ULL;
};

template<class ContainerAllocator>
struct DataType< ::region_events::region_eventsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "region_events/region_eventsResponse";
  }

  static const char* value(const ::region_events::region_eventsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::region_events::region_eventsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stepped\n\
\n\
";
  }

  static const char* value(const ::region_events::region_eventsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::region_events::region_eventsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stepped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct region_eventsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::region_events::region_eventsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::region_events::region_eventsResponse_<ContainerAllocator>& v)
  {
    s << indent << "stepped: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stepped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REGION_EVENTS_MESSAGE_REGION_EVENTSRESPONSE_H
