// Generated by gencpp from file region_events/region_events.msg
// DO NOT EDIT!


#ifndef REGION_EVENTS_MESSAGE_REGION_EVENTS_H
#define REGION_EVENTS_MESSAGE_REGION_EVENTS_H

#include <ros/service_traits.h>


#include <region_events/region_eventsRequest.h>
#include <region_events/region_eventsResponse.h>


namespace region_events
{

struct region_events
{

typedef region_eventsRequest Request;
typedef region_eventsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct region_events
} // namespace region_events


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::region_events::region_events > {
  static const char* value()
  {
    return "9df8f2f743a5e6ba6981f0ecdb4d3549";
  }

  static const char* value(const ::region_events::region_events&) { return value(); }
};

template<>
struct DataType< ::region_events::region_events > {
  static const char* value()
  {
    return "region_events/region_events";
  }

  static const char* value(const ::region_events::region_events&) { return value(); }
};


// service_traits::MD5Sum< ::region_events::region_eventsRequest> should match 
// service_traits::MD5Sum< ::region_events::region_events > 
template<>
struct MD5Sum< ::region_events::region_eventsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::region_events::region_events >::value();
  }
  static const char* value(const ::region_events::region_eventsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::region_events::region_eventsRequest> should match 
// service_traits::DataType< ::region_events::region_events > 
template<>
struct DataType< ::region_events::region_eventsRequest>
{
  static const char* value()
  {
    return DataType< ::region_events::region_events >::value();
  }
  static const char* value(const ::region_events::region_eventsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::region_events::region_eventsResponse> should match 
// service_traits::MD5Sum< ::region_events::region_events > 
template<>
struct MD5Sum< ::region_events::region_eventsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::region_events::region_events >::value();
  }
  static const char* value(const ::region_events::region_eventsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::region_events::region_eventsResponse> should match 
// service_traits::DataType< ::region_events::region_events > 
template<>
struct DataType< ::region_events::region_eventsResponse>
{
  static const char* value()
  {
    return DataType< ::region_events::region_events >::value();
  }
  static const char* value(const ::region_events::region_eventsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REGION_EVENTS_MESSAGE_REGION_EVENTS_H
