(cl:defpackage ardupilot_sitl_gazebo_plugin-srv
  (:use )
  (:export
   "RELEASEAPMLAPSELOCK"
   "<RELEASEAPMLAPSELOCK-REQUEST>"
   "RELEASEAPMLAPSELOCK-REQUEST"
   "<RELEASEAPMLAPSELOCK-RESPONSE>"
   "RELEASEAPMLAPSELOCK-RESPONSE"
   "TAKEAPMLAPSELOCK"
   "<TAKEAPMLAPSELOCK-REQUEST>"
   "TAKEAPMLAPSELOCK-REQUEST"
   "<TAKEAPMLAPSELOCK-RESPONSE>"
   "TAKEAPMLAPSELOCK-RESPONSE"
  ))

